services:
  backend:
    container_name: tron_backend
    build:
      dockerfile: ./Dockerfile
      context: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: tron_db
    image: postgres:16.1-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - .env

volumes:
  pgdata:
