"""init migration

Revision ID: f452b38a61c3
Revises: 
Create Date: 2024-12-23 16:27:32.317532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f452b38a61c3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "address_queries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("trx_balance", sa.Float(), nullable=True),
        sa.Column("bandwidth", sa.Integer(), nullable=True),
        sa.Column("energy", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_address_queries_address"), "address_queries", ["address"], unique=False
    )
    op.create_index(
        op.f("ix_address_queries_id"), "address_queries", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_address_queries_id"), table_name="address_queries")
    op.drop_index(op.f("ix_address_queries_address"), table_name="address_queries")
    op.drop_table("address_queries")
    # ### end Alembic commands ###
